print("Evaluación N°1 Programación y Redes Virtualizadas")
print("Integrantes:")
print("- Leopoldo")
nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
codigo_seccion = input("Ingrese su código de sección: ")
sede = input("Ingrese su sede: ")
print("\nInformación ingresada:")
print(f"Nombre: {nombre}")
print(f"Apellido: {apellido}")
print(f"Código de sección: {codigo_seccion}")
print(f"Sede: {sede}")
